### ISSUE TITLE
Support for iGrill v3

### ISSUE THREAD

**Issue by christiaaneggink** [1mckenna/esp32_iGrill#1]
Awesome @1mckenna, I had given up hope to ever get this working.

For those interested, I got this working for the iGrill v3 by changing the SERVICE_UUID in line 16:
static BLEUUID SERVICE_UUID("6E910000-58DC-41C7-943F-518B278CEA88"); //iGrillv3 Service

**Comment by 1mckenna** [comment]
Thanks for letting me know! Once I finish up the last bit of changes for the wifi/mqtt side I'll add this in so it'll work for either device without any code changes.

**Comment by 1mckenna** [comment]
@christiaaneggink iGrillv3 support has been added. When you have some free time can you flash the new codebase and let me know if you run into any issues.

**Comment by christiaaneggink** [comment]
@1mckenna, I tried flashing it to my ESP32 Dev Kit V1 yesterday, but the sketch appears to be too big for my board. What board are you using? Did you change partition table sizes?

`Sketch uses 1483773 bytes (113%) of program storage space. Maximum is 1310720 bytes.` 

EDIT: I changed the partition scheme to: No OTA, 2MB app and 2MB SPIFFS, this did the trick and the code flashed to the ESP32 without issue. The WiFi and MQTT setup was easy and the ESP connects to the iGrill v3!

`13:31:34.146 -> [II] Connecting to iGrill Device: 70:91:8f:07:0f:91`
`13:31:36.718 -> [II]  - Created client`
`13:31:36.718 -> [II]  - Connected to iGrill BLE Server`
`13:31:36.901 -> [II]  - iGrill Pair Status: Paired`
`13:31:37.724 -> [II]  - Performing iGrill App Authentication`
`13:31:43.208 -> [II]  - Writing iGrill App Challenge...`
`13:31:43.731 -> [II]  - Reading iGrill Device Challenge`
`13:31:44.278 -> [II]  - Writing Encrypted iGrill Device Challenge...`
`13:31:44.312 -> [II]  - Authentication Complete`
`13:31:46.398 -> [II] Connecting to MQTT...`
`13:31:51.722 -> [II] MQTT connected`
`13:31:51.722 -> [II]  - Setting up Battery Characteristic...`
`13:31:51.789 -> [II]  - Setting up Probes...`
`13:31:51.825 -> [II]   -- Probe 1 Setup!`
`13:31:51.896 -> [II]   -- Probe 2 Setup!`
`13:31:51.964 -> [II]   -- Probe 3 Setup!`
`13:31:52.032 -> [II]   -- Probe 4 Setup!`

In my case temperatures are published to Home Assistant, which also works like a charm. 
I do question the values that are published, as it shows temperatures as low as 1-2 degrees C. I need to look into this a bit more.

Looks very promising - thanks for this!

**Comment by 1mckenna** [comment]
Awesome! 

The probes according to the Weber docs  can read temps from -50* C to 380* C. I have my device set to use Fahrenheit though and never tried in Celsius. I'll change my device today and see what readings I get on my side.

Does the value being published to MQTT match what's shown on the display?  I set the unit_of_measurement to degree F in the probes mqtt autodiscovery configs (see line 916) and don't think that would affect the temp shown (unless maybe HA is doing some temp conversion automatically?). I'll push an update later today to make that easily configurable for those that have the device reading in Celsius in the config.h.

Might also want to make sure the probes are reading the correct temps as I've had a probe go bad before. Easiest way to check is to boil a cup of water and put the probe in it since it should read ~100* C/212* F.

**Comment by christiaaneggink** [comment]
Setting the unit_of_measurement to degrees C for all probes did the trick. Home Assistant indeed did auto conversion of the published temperatures and interpreted the published value as degrees F, although it was degrees C :-)

**Comment by 1mckenna** [comment]
I just pushed new code that enables the ability to select metric degrees from the config portal. 
Since I added a new setting that wasn't there previously after flashing you will need to put the device into configuration mode and then open the portal and re-enter all the information **(even if the old data is shown)** and make the degree selection before saving.

**Comment by christiaaneggink** [comment]
Excellent, thank you.

Just out of curiosity, how often does your v2 publish its battery level? I have been testing the v3 for a while now, but have not yet seen an update on the battery level.

**Comment by 1mckenna** [comment]
The way the code works is once we connect to the iGrill Device via BLE we then register to be notified via our callback once the  batteryCharacteristic changes (i.e. if the battery level changes on the device we get notified of its new value) on notification of the change we then publish the battery level to MQTT. 

I usually see a battery message every few minutes, if you leave it up and running for ~5 mins I would suspect you should see at least one battery level message being published.
