### ISSUE TITLE
Instructions not quite clear.

### ISSUE THREAD

**Issue by cptcave** [1mckenna/esp32_iGrill#31]
Forgive me as I am a bit of a noob.  I have followed the instructions up to the merging of the files and have hass talking to my esp32 and my iGrill v2 is reporting data back to hass through the esp32.  The automatically recognized mqtt device tends to drop connection at random and is unstable. I suspect that is what the rest of the instructions are to address.  I understand appending the files, but the instruction to replace with the iGrill mac address is not clear.  In none of the code in any of the files can I find a mac address to replace. I see examples of several preconfigured existances of esp32_iGrill but not in ALL files as the instruction indicates.  Is there a place in every file to place the mac? Also, what is the current working version of hassio that supports this integration?

Thank you for the great work!

**Comment by 1mckenna** [comment]
For the instability issue please check and ensure the esp32 board library version you are using is 2.0.4.

Probably the easiest way to get your mac address now that you have connected the iGrill to HA once is to open your HA Dashboard then Settings > Devices and Services > Devices Tab > filter for igrill. Listed there you should see a device that starts with igrill_. The part after the _ is the devices mac address. Now with your device name you should just be able to replace my iGrill device name (igrill_d481ca223348) in the configs with yours.

There used to be a manual MQTT sensor you needed to configure to monitor the iGrill's status, but with the latest changes I made this sensor now gets automatically configured and setup via MQTT Autodiscovery. Is that what you are referring to? 

This will work with any Home Assistant installation since it's just using MQTT to send over the device and sensor information.

**Comment by cptcave** [comment]
Thank you for responding. I had used 2.0.4 but at some point i was asked to do an update, so i did automatically.   Ill change it back.

I was referring to these instructions

[Image]
 It was here I could not find the place to change the Mac address.

Again, this is great. I saw bendikwa's version but it required too much coding and work to get it going.  This is so far the easiest way to make this happen.

Thanks,
Kevin
________________________________

**Comment by cptcave** [comment]
***Edited - New information after update

Ok, duh, I see now about the mac.  I did not realize the mac was the number following igrill. Even though you specifically note it.  Now the format is wrong on my dashboard.  I only get battery levels and probe temps.  Everything else has errors. I get "entity not available".  You list all of the mqtt topics. Am I supposed to list those somehwere? I feel like something isn't getting defined somewhere. 

I am getting the state now that I updated to the most recent version, however, I'm still getting the same errors everywhere else.
![image](https://github.com/1mckenna/esp32_iGrill/assets/84912920/ffc180ae-63b3-44a2-a80b-4303edfb3949)
![image](https://github.com/1mckenna/esp32_iGrill/assets/84912920/62d7c7ca-e261-41ed-bf9f-19690b661ced)

More is working after the update, but still showing errors, specifically with the notify.admin service call in automations.  I don't see where I can set the upper and lower limits for a cook.  I do like this feature in the app and while there seems to be some way to do it, I cannot figure it out.

Also since changing the board firmware back to 2.0.4 the connection seems to work flawlessly. Considering how bad Weber has been at the software side of this application, the iGrill v2 is rock solid and much more improved by this bit of kit.

**Comment by 1mckenna** [comment]
To resolve most of those you just need to create the input_number helpers either in yaml or  through the HA UI using the values and names shown [here](https://github.com/1mckenna/esp32_iGrill/blob/main/ha_example_config/input_numbers/igrill.yaml)

The temperature alerting stuff will need to be setup by copying the yaml in the sensor folder to your template sensor yaml [template sensor info](https://www.home-assistant.io/integrations/template/)

The notify admin service is what I have setup on my side for notifying my mobile through the companion app. You could replace the notify.admin with notify.mobile_app_yourdevicename.
